### ISSUE TITLE
hosting on iis

### ISSUE THREAD

**Issue by erichexter** [sbarski/dashing.net#12]
I was able to get the dashboard running on a dev machine using IIS Express, but when I host it on IIS on an azure VM or on an Azure website, the api/events/ call never completes, it statys open ( in chrome dev tools) is there a know fix, IIS configurtion to get the SSE working on iis 8 ?

**Comment by ryan-barry** [comment]
Same issue here.  No call backs.

**Comment by erichexter** [comment]
I gave up on this and created a new dashboard using signalr pulling in the same client libraries

**Comment by ryan-barry** [comment]
I ended up getting it working. But ya only Chrome.

**Comment by erichexter** [comment]
What steps did you do to get it working?

On Thursday, October 24, 2013, ryan-barry wrote:

> I ended up getting it working. But ya only Chrome.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sbarski/dashing.net/issues/12#issuecomment-27019658
> .

## 

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by ryan-barry** [comment]
So I ended up pointing the web site to a sub directory that had the full project and augmented the eventsource path to hit the sub-dir.  I had signalr working on the box for another project so I am not sure if that setup had any effect.  I hopefully will get some time to repeat the setup next week.
