### ISSUE TITLE
Deploying to IIS

### ISSUE THREAD

**Issue by jacko873** [sbarski/dashing.net#17]
I know the bug for this was already closed but there was really no resolution there,

i have been trying to deploy dashiong.net to iis all day without any luck.

has anybody managed todo this? do anyone have any guidance?

thanks

**Comment by vkairys** [comment]
What problems are you facing?
I had problems when decided to set virtual path "/dashing" to the application.
In my case I had to:
- Add  `Batman.config.viewPrefix = 'dashing/views'` in the [dashing.coffee](https://github.com/sbarski/dashing.net/blob/7d27ec3a4b04be04dfe0b0ed1863fae8e74ead13/src/dashing.net/Scripts/dashing.coffee)
- Change [dashing.coffee#L92](https://github.com/sbarski/dashing.net/blob/7d27ec3a4b04be04dfe0b0ed1863fae8e74ead13/src/dashing.net/Scripts/dashing.coffee#L92)  to `source = new EventSource('/dashing/api/events')` 
- Change [Global.asax.cs#L39](https://github.com/sbarski/dashing.net/blob/7d27ec3a4b04be04dfe0b0ed1863fae8e74ead13/src/dashing.net/Global.asax.cs#L39) to `if (url.StartsWith("/dashing/views/") && url.EndsWith(".html"))`
