### ISSUE TITLE
Base paths for views are incorrect for virtual directory setup

### ISSUE THREAD

**Issue by alexmackey** [sbarski/dashing.net#3]
To recreate:
Setup virtual dir to MVC apps root directory
Browse site
Get uncaught Error: Could not load view from /list in application-js:11922 (seems to be going to http://localhost/views/list.html rather than http://localhost/dashboard/views/list.html)

**Comment by sbarski** [comment]
This issue should now be fixed in the current dev/master branches. The problem was that static resources (html, images, css, etc..) were not being piped through the standard IIS pipeline in some circumstances. All requests are now routed through the pipeline as per normal.
