### ISSUE TITLE
Solarwinds Auto Authentication

### ISSUE THREAD

**Issue by gsaxam** [sbarski/dashing.net#7]
Thanks for a great tool. I am trying to pull solarwinds data into my dashboard and was wondering if there's a way to auto authenticate into solarwinds in dashing.net because solarwinds pops up a login box and I have to manually log-in.

**Comment by sbarski** [comment]
Hi. I am not too familiar with solarwinds but a way to solve your problem would be to build a widget which authenticates with solarwinds, pulls the required data out and then pushes it onto dashing for display. 

Have a look at the twitter widget for an example. It authenticates with twitter, grabs some tweets and displays them on the dashboard (the user doesn't need to login because everything is done via the back-end). 

Hope that helps!

**Comment by gsaxam** [comment]
Thanks. Actually it turned out to be easier using DirectLink urls from Solarwinds.

**Comment by ghost** [comment]
gsaxam,

Care to share your configuration/widgets? Trying to pull SW data into dashing.

**Comment by gsaxam** [comment]
I ended up creating a direct link account and added the graphs to that
list. Now, it does not ask for any kind of authentication.

hope it helps!

On Wed, Jan 8, 2014 at 6:06 PM, jsanchez23 notifications@github.com wrote:

> gsaxam,
> 
> Care to share your configuration/widgets? Trying to pull SW data into
> dashing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sbarski/dashing.net/issues/7#issuecomment-31890273
> .

## 

Regards,
Saksham Ghimire

**Comment by ghost** [comment]
One more question if I could? How did get the data int dashing from the page? Sorry if this sounds dumb, but I am trying to get this working, and I am not a programmer.

**Comment by around01** [comment]
I'm trying to do the same thing with Solarwinds, was there an update to this?

**Comment by sapg** [comment]
I'd love to get a bit more detail on this too.

**Comment by gsaxam** [comment]
What I had to do to get it working was to ask my SolarWinds admin to create "directlink" credentials which is just like a service account in solarwinds. When you assign the directlink credentials to the solarwinds links, they don't need authentication anymore. hope this helps! Hit the SolarWinds docs on learning more about directlinks.

**Comment by sapg** [comment]
I was hoping you'd share your dashboard, widget and job code or are you just displaying Solarwinds in Dashing?
